
version: 2.1

executors:
  windows: win/default

orbs :
  node : circleci/node@3.0.0
  win : circleci/windows@2.2.0
jobs :
  test :
    parameters:
      os:
        type: executor
      is-linux:
        type: boolean
        default: true
      is-mac:
        type: boolean
        default: false
    executor: << parameters.os >>
    steps :
      - checkout
      - when:
          condition: << parameters.is-linux >>
          steps:
            - node/install:
                node-version: 12.9.1
            - run : sudo npm -g install willbe@stable
      - unless:
          condition: << parameters.is-linux >>
          steps:
            - run : nvm install 12.9.1
            - run : nvm use 12.9.1
            - run : npm -g install willbe@stable
      - when:
          condition: << parameters.is-mac >>
          steps:
            - run : sudo chown -R 501:20 ~/.npm
      - run : npm install
      - run : npm test

workflows :
    test :
      jobs :
        - test:
            name : Windows
            os: windows
            is-linux: false
